import fileinput
import os


def export_hotspots(hotspots: dict, file_directory):
    """Exports a list of hotspots to the 3dButtons.dat"""
    """Will replace the lines of an existing 3dButtons.dat with new data"""

    if not hotspots or len(hotspots) == 0:
        return
    
    hotspots_filepath = os.path.join(file_directory, "3dButtons.dat")

    # 3dButtons.dat already exists
    if os.path.exists(hotspots_filepath):
        # first: check existing callbacks in the file and update them
        with fileinput.input(hotspots_filepath, inplace=True) as hotspots_file:
            for line in hotspots_file:
                if line.startswith("//") or len(line.strip()) <= 1:
                    print(line, end="")
                else:
                    callback_name = line.split(maxsplit=1)[0]
                    if callback_name in hotspots.keys():
                        hotspot = hotspots.pop(callback_name)
                        print(f"{hotspot}\n", end="")
                    else:
                        print(line, end="")
        
        # Second: add the remaining hotspots to the end of the file
        with open(hotspots_filepath, "a") as hotspots_file:
            for hotspot in hotspots.values():
                hotspots_file.write(f"{hotspot}\n")
    else:
        # create a new file
        with open(hotspots_filepath, "w") as hotspots_file:
            # Add a header
            hotspots_file.write("// 3D Button File for Falcon BMS\n")
            hotspots_file.write("// Generated by BMS Blender Plugin\n\n")
            
            for hotspot in hotspots.values():
                hotspots_file.write(f"{hotspot}\n")
